#ifndef OPTSET_SIMPLEOPTIONS
#define OPTSET_SIMPLEOPTIONS

#include <string>

/**
A collection of simple options for testing.

Automatically generated config/options file.
*/
struct SimpleOptions
{
        std::string FeedbackTone; //!< The tone/colour of feedback generated by the test
        const std::string DefaultFeedbackTone = "blunt"; //!< default value for 'FeedbackTone' if no value is specified
        int BonusMarks; //!< The number of bonus marks to assign
        const int DefaultBonusMarks = 0; //!< default value for 'BonusMarks' if no value is specified
};

#endif