#ifndef OPTSET_SIMPLEOPTIONS
#define OPTSET_SIMPLEOPTIONS

#include <string>
#include <vector>
#include "utils/configuration/ConfigOption.hpp"

/**
A collection of simple options for testing.

Automatically generated config/options file.
*/
struct SimpleOptions
{
    std::string FeedbackMessage; //!< The tone/colour of feedback generated by the test
    const std::string DefaultFeedbackMessage = "No feedback provided."; //!< default value for 'FeedbackMessage' if no value is specified
    int BonusMarks; //!< The number of bonus marks to assign
    const int DefaultBonusMarks = 0; //!< default value for 'BonusMarks' if no value is specified

    void Initialise(std::vector<ConfigOption> &options);
};

#endif